// apps/react-remote-a/src/bootstrap.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import NxWelcome from './app/nx-welcome';

class MfeReactApp extends HTMLElement {
  connectedCallback() {
    const container = document.getElementsByTagName('mft-wc-wrapper')[0] as HTMLElement;
    const root = createRoot(container);
    root.render(
      <StrictMode>
        <NxWelcome title="react-remote-a" />
      </StrictMode>,
    );
  }
}

customElements.define('react-remote-a-bootstrap-page', MfeReactApp);

export default MfeReactApp;

// apps/react-remote-b/src/bootstrap.tsx
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';

import App from './app/app';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <StrictMode>
    <App />
  </StrictMode>,
);

export default function bootstrap() {
  return null;
}
